Supported gnu auto generated test cases
riscv-non-isa/rvv-intrinsic-doc pull request #272
Opened 2023-09-15 03:23 UTC by yulong-plct

Hi, @eopXD :
This PR adds the implementation for gnu auto generated test case that I did together with @Incarnation-p-lee and @xl0714.
Please review it.
It is worth noting that this PR only generates cases, and the rest of the content will be in another PR.
Thanks!

2023-09-15 09:03 UTC, eopXD reviewed
Thank you for the organized PR!

- Nit: In my opinion, the commit "create folder for gnu auto generated test cases" should be ordered after your edits to the generator. Since `--toolchain-type` is not yet supported at the first place.
- Please capitalize the first letter of your commit message
- Please add another commit to separate the current target in the makefile `gen-test` to consist of `gen-llvm-test` and `gen-gnu-test`. Then, please try to commit the test case additions under `auto-generated/`  with `make git-commit-all` and see if things work out.
- Please check the CI under your branch, make sure the CI passes.

2023-09-15 14:37 UTC, Incarnation-p-lee requested changes

2023-09-15 14:37 UTC, Incarnation-p-lee commented on rvv-intrinsic-generator/Makefile
> +	rm $(1)/*.c $(1)/*.C -f
I suppose we don't generate source files like "*.C" anymore, @eopXD  can help to confirm about this.

2023-09-15 14:37 UTC, Incarnation-p-lee commented on rvv-intrinsic-generator/Makefile
> +gen-gnu-test: gnu-overloaded-test gnu-non-overloaded-test
who will consume this target `gen-gnu-test` when overall making?

2023-09-15 14:37 UTC, Incarnation-p-lee commented on rvv-intrinsic-generator/Makefile
> +	$(call gen_tests,$(DIR)/gnu-api-tests,non-overloaded-test,--toolchain-type gnu)
I think the first PR would be adding the gnu target without any further action to take, and then committing the gnu auto-generated folder.

You can reference [this](http://principles-wiki.net/principles:keep_it_simple_stupid) and [this](https://arxiv.org/vc/cs/papers/0701/0701021v1.pdf) doc for more details.

2023-09-17 04:47 UTC, yulong-plct commented
I will make modifications according to the above suggestions and submit a new PR.
Thanks a lot! @eopXD @Incarnation-p-lee

2023-09-18 05:04 UTC, eopXD commented
> I will make modifications according to the above suggestions and submit a new PR. Thanks a lot! @eopXD @Incarnation-p-lee

I think you don't need to open up another PR, you can force push to the same brunch and this PR will be updated.

2023-09-18 05:19 UTC, eopXD commented
Additionally, I think we can also add a Github Action to verify the test cases you have generated here upon the latest GNU toolchain here, or have you already planned to include this in a separate PR?

2023-09-18 06:35 UTC, closed without merging